# docker-compose.dev.yml
# This file is used to override settings in docker-compose.yml for development purposes.
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  backend:
    build:
      target: dev
    volumes:
      - ./backend:/app  # Mount entire backend directory for hot reloading
    depends_on:
      db_local:
        condition: service_healthy

  db_local:
    image: postgres:latest
    container_name: postgres
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    depends_on:
      - db_local
    restart: on-failure