# docker-compose.dev.yml
# This file is used to override settings in docker-compose.yml for development purposes.
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  backend:
    build:
      target: dev
    volumes:
      - ./backend:/app # Mount entire backend directory for hot reloading
    depends_on:
      db_local:
        condition: service_healthy

  frontend:
    image: imbios/bun-node
    working_dir: /app
    env_file:
      - ./.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '5173:5173'
    command: sh -c "bun install && bun run dev --host"
    restart: on-failure
    depends_on:
      - backend
