services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.prod
    ports:
      - '6005:6005'
    restart: on-failure
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.prod
    ports:
      - '6006:6006'
    env_file:
      - ./.env
    restart: on-failure
    depends_on:
      db_local:
        condition: service_healthy

  db_local:
    image: postgres:latest
    container_name: postgres
    env_file:
      - ./.env
    ports:
      - '6007:6007'
    command: ['-p', '6007']
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -p 6007']
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '6009:6009'
    depends_on:
      - db_local
    restart: on-failure
    env_file:
      - ./.env
    environment:
      PGADMIN_LISTEN_PORT: 6009
