root         = "."
testdata_dir = "testdata"
tmp_dir      = "tmp"

[build]
cmd         = "go build -o ./tmp/main ."
bin         = "./tmp/main"
delay       = 1000
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["tmp", "vendor", "testdata"]

[log]
time = true
