# Stage 1: Development stage with hot reload
FROM golang:1.24.2-alpine
WORKDIR /app
RUN go install github.com/air-verse/air@latest
COPY go.mod go.sum ./
RUN go mod download
COPY . .
EXPOSE 6006
CMD ["air", "-c", ".air.toml"]
