package main

import (
	"fmt"
	"log"
	"net/http"
	"os"

	"microservice-architecture-builder/backend/controller"
	"microservice-architecture-builder/backend/data"
	"microservice-architecture-builder/backend/server"
	"microservice-architecture-builder/backend/service"

	_ "microservice-architecture-builder/backend/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title Microservice Architecture Builder API
// @version 1.0
// @description This is the API documentation for the Microservice Architecture Builder backend.
// @host localhost:8080
// @BasePath /api
func main() {
	// Initialize dependencies
	dsn := os.Getenv("POSTGRES_DSN")
	store, err := data.NewPostgresStore(dsn)
	if err != nil {
		log.Fatalf("Failed to connect to PostgreSQL: %v", err)
	}
	boardService := service.NewBoardService(store)
	boardController := controller.NewBoardController(boardService)

	r := server.NewServer(boardController)

	// Start server
	port := ":8080"
	fmt.Printf("Server starting on port %s\n", port)
	log.Fatal(http.ListenAndServe(port, r))
}
