on:
  workflow_call:

jobs:
  trigger_deploy:
    name: Trigger deploy
    runs-on: ubuntu-latest
    env:
      RAN_ON_GITHUB: ${{ secrets.RAN_ON_GITHUB }}
    steps:
      - name: Trigger Netlify deploy
        if: ${{ env.RAN_ON_GITHUB  == 'true' && success() }}
        run: |
          echo "Secret value: ${{ secrets.NETLIFY_BUILD_HOOK_URL }} env secres ${{ env.RAN_ON_GITHUB }}"
          curl -X POST ${{ secrets.NETLIFY_BUILD_HOOK_URL }}
