on:
  workflow_call:
    secrets:
      RAN_ON_GITHUB:
        required: true
      NETLIFY_BUILD_HOOK_URL:
        required: true

jobs:
  trigger_deploy:
    name: Trigger deploy
    runs-on: ubuntu-latest
    env:
      RAN_ON_GITHUB: ${{ secrets.RAN_ON_GITHUB }}
    steps:
      - name: Trigger Netlify deploy
        if: ${{ env.RAN_ON_GITHUB == 'true'  }}
        run: |
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          ENCODED_MESSAGE=$(python3 -c "import urllib.parse; print(urllib.parse.quote('''$COMMIT_MESSAGE'''))")
          curl -X POST "${{ secrets.NETLIFY_BUILD_HOOK_URL }}?trigger_title=${ENCODED_MESSAGE}"
