name: Tests and deploy
on:
  push:
    branches:
      - master
      - feat-55-test-suite
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

jobs:
  tests:
    name: Run E2E Tests
    timeout-minutes: 60
    env:
      RAN_ON_GITHUB: ${{ secrets.RAN_ON_GITHUB }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: FAIL
        run: exit 1
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - name: Upload test report
        if: ${{ env.RAN_ON_GITHUB == 'true' && !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  triggerDeploy:
    name: Call Deploy job
    needs: tests
    uses: ./.github/workflows/callable-deploy.yml
    secrets: inherit

  notifyMe:
    if: always()
    env:
      RAN_ON_GITHUB: ${{ secrets.RAN_ON_GITHUB }}
    name: Send Deployment Notifications
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Notify on failure
        if: ${{ env.RAN_ON_GITHUB == 'true' && !success() }}
        run: curl -X POST ${{ secrets.N8N_FAILURE_NOTIFICATION_URL }}
      - name: Notify on success
        if: ${{ env.RAN_ON_GITHUB == 'true' && success() }}
        run: curl -X POST ${{ secrets.N8N_SUCCESS_NOTIFICATION_URL }}
